version: "3.8"

services:
  editor:
    image: editor-app
    container_name: app
    environment:
      QUEUE_WORKERS_COUNT: 1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    volumes:
      - '.:/usr/local/www/docs/'
      - './config/nginx/default.conf:/etc/nginx/conf.d/default.conf'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
  site:
    image: docsy/docsy-example
    build:
      context: .
    command: server
    ports:
      - "1313:1313"
    volumes:
      - .:/src
