version: "3.8"

services:
  editor:
    image: editor-app
    container_name: app
    environment:
      QUEUE_WORKERS_COUNT: 1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9001:80"
      - "9306:9306"
      - "9312:9312"
      - "9007:80"
    volumes:
      - '${PWD}:/usr/local/www/editor'
      - '${PWD}/config/nginx/default.conf:/etc/nginx/conf.d/default.conf'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
  site:
    image: docsy/docsy-example
    build:
      context: .
    command: server
    ports:
      - "1313:1313"
    volumes:
      - .:/src
