edit:
  path: /edit
  methods: GET
  controller: App\Controller\EditorController::edit

save:
  path: /api/save
  methods: POST
  controller: App\Controller\EditorController::save

delete:
  path: /api/delete
  controller: App\Controller\EditorController::delete